### ISSUE TITLE
Browsers can access parent directory. (and therefore whole filesystem)

### ISSUE THREAD

**Issue by r4dian** [sublee/flask-autoindex#18]
by accessing http://localhost:80/.\..

note: tested on Windows with a quick hack to workaround #17 (as suggested on #14 ), but I think it would also work on Linux etc.

**Comment by hiredgunhouse** [comment]
Wow, that's bad and it's even worse that theres no response to this issue :(
This makes me think about ditching AutoIndex completely.

**Comment by r4dian** [comment]
If you're on a different OS can you confirm if it happens? I guess there's no interest in supporting Windows here for some reason.

**Comment by narenst** [comment]
I don't see this on OSX

**Comment by dbr** [comment]
This vulnerability is present with the server running on Linux (with Flask-AutoIndex 0.6.1)

Note that some browsers normalise away `..` in path, e.g if I navigate to `http://localhost:8000/../../../../../etc/passwd` then Firefox will change this to `http://localhost:8000/etc/passwd`

It can be seen using something simpler like `curl`, e.g

    curl http://localhost:8000/../../../../../etc/passwd

**Comment by sublee** [comment]
It's fixed since 0.6.2. If there's a remaining issue, please let me know to reopen it.
