### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by timokau** [sublee/flask-autoindex#38]
Importing flask.ext.silk is now an error in flask (not just a warning, see #36). This causes the tests to fail. Could you cut a new release including the fix, #37?

**Comment by sublee** [comment]
Thanks for the great work.  Did you mean I need to publish `0.5.1` to PyPI including #37?

**Comment by timokau** [comment]
Oh, somehow github swallowed the email notification for this issue.

I meant that a new release from the current master (`0.6.1` or `0.7`) would be nice.

**Comment by sublee** [comment]
Sorry for my late response. I've just uploaded Flask-AutoIndex 0.6.1.

**Comment by timokau** [comment]
Thanks!
