### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by general03** [sublee/flask-autoindex#45]
Hello sublee,

I pushed merge request few weeks ago https://github.com/sublee/flask-autoindex/pull/43 but there are no update on pypi (and I need it)
I know you don't maintain this repo but if you want I can manage the repo to continue the project

Thanks

**Comment by sublee** [comment]
Hi @general03,

That sounds great. Please email me with your PyPI username to get permission at PyPI.

Thank you so much.

**Comment by sublee** [comment]
@general03 I also can transfer this repository to you. How do you think about?

**Comment by general03** [comment]
Sure, I sent you mail with my information

Thanks

**Comment by sublee** [comment]
Thank you so much. I'm closing this issue. We will talk in Email.
